### ISSUE TITLE
Bump to latest core version

### ISSUE THREAD

**Issue by nitayk** [ua-parser/uap-scala#123]
It seems that the core module is not up-to-date for 0.11 version

**Comment by phucnh** [comment]
@nitayk I've updated the latest uap-core and publish v0.12.0 to maven. Please check and let me know if any problem.

**Comment by nitayk** [comment]
What is strange to me is that it fails to parse some  IOS 13 / 14 UA's - which shouldn't happen as they are our for some time now.
Are we sure this is up-to-date? I've added some custom parsers to support those versions and I don't seem to be able to remove them

**Comment by phucnh** [comment]
@nitayk Thank you for the reply. I will check again.
Could you please give me an example of failed parsing user agent?

**Comment by nitayk** [comment]
iOS14 browswer

- Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

iOS14 native

- folk/10 CFNetwork/1183 Darwin/20.0.0

iOS13 examples:

- American%20Dad!%20Apocalypse%20Soon/1609 CFNetwork/1121.2.2 Darwin/19.3.0
- Golf%20Clash/1670 CFNetwork/1120 Darwin/19.0.0
- magictiles/2002251817 CFNetwork/1107.1 Darwin/19.0.0
- braintest/0.4 CFNetwork/1098.7 Darwin/19.0.0

We use custom parsers for now:
`OSParser.fromList {
    List(
      Map(
        "regex" -> "CFNetwork/1.* Darwin/(19)\\.\\d+",
        "os_replacement" -> "iOS",
        "os_v1_replacement" -> "13"
      ),
      Map(
        "regex" -> "CFNetwork/1.* Darwin/(20)\\.\\d+",
        "os_replacement" -> "iOS",
        "os_v1_replacement" -> "14"
      )
    )
  }`

But I worry about what we might be missing. Any thoughts?

**Comment by phucnh** [comment]
@nitayk 
Thank you.
My check result is as follows:
```console
$ ammonite # get from https://ammonite.io/
@ import $ivy.`org.uaparser::uap-scala:0.12.0`
@ import org.uaparser.scala.Parser
@ val parser = Parser.default

@ parser.parse("Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148")
// res01:org.uaparser.scala.Client = Client(UserAgent("Mobile Safari UI/WKWebView", None, None, None), OS("iOS", Some("14"), Some("0"), None, None), Device("iPhone", Some("Apple"), Some("iPhone")))

@ parser.parse("folk/10 CFNetwork/1183 Darwin/20.0.0") 
// res02:org.uaparser.scala.Client = Client(UserAgent("folk", Some("10"), None, None), OS("iOS", Some("14"), None, None, None), Device("iOS-Device", Some("Apple"), Some("iOS-Device")))

@ parse.parse("American%20Dad!%20Apocalypse%20Soon/1609 CFNetwork/1121.2.2 Darwin/19.3.0")
// res03:org.uaparser.scala.Client = Client(UserAgent("American%20Dad!%20Apocalypse%20Soon", Some("1609"), None, None), OS("iOS", Some("13"), Some("3"), Some("1"), None), Device("iOS-Device", Some("Apple"), Some("iOS-Device")))

parser.parse("Golf%20Clash/1670 CFNetwork/1120 Darwin/19.0.0") 
// res04:org.uaparser.scala.Client = Client(UserAgent("Golf%20Clash", Some("1670"), None, None), OS("iOS", Some("13"), None, None, None), Device("iOS-Device", Some("Apple"), Some("iOS-Device")))

@ parser.parse("magictiles/2002251817 CFNetwork/1107.1 Darwin/19.0.0")
// res05:org.uaparser.scala.Client = Client(UserAgent("magictiles", Some("2002251817"), None, None), OS("iOS", Some("13"), None, None, None), Device("iOS-Device", Some("Apple"), Some("iOS-Device")))

@ parser.parse("braintest/0.4 CFNetwork/1098.7 Darwin/19.0.0")
// res06:Client(UserAgent("braintest", Some("0"), Some("4"), None), OS("iOS", None, None, None, None), Device("iOS-Device", Some("Apple"), Some("iOS-Device")))
```

With `uap-scala:0.12.0`, except `braintest/0.4 CFNetwork/1098.7 Darwin/19.0.0`, the OS and version are parsed.

**Comment by phucnh** [comment]
> @ parser.parse("braintest/0.4 CFNetwork/1098.7 Darwin/19.0.0")
> // res06:Client(UserAgent("braintest", Some("0"), Some("4"), None), OS("iOS", None, None, None, None), Device("iOS-Device", Some("Apple"), Some("iOS-Device")))

After some checks, maybe the OS version can not be parsed because there is no rule for `CFNetwork/1098.7` for iOS 13 in `uap-core` which is where uap-scala gets its data from.
https://github.com/ua-parser/uap-core/blob/2b643ba734ce509c77d8896fe43256ba9dc4f3a8/regexes.yaml#L1477-L1496

All rules assume iOS 13 UA should be `CFNetwork/11.{0,100}`, so `CFNetwork/1098.7` can not be matched.
I think we need an additional rule like `'CFNetwork/1[01].{0,100} Darwin/(19)\.\d+'` for iOS 13 in `uap-core`.

I think you should create an issue in [uap-core](https://github.com/ua-parser/uap-core)

**Comment by nitayk** [comment]
Ok, I will
Thanks (will use the custom parsers for now)

**Comment by phucnh** [comment]
Thanks a lot!
