### ISSUE TITLE
Publish new version to maven repo

### ISSUE THREAD

**Issue by thyandrecardoso** [ua-parser/uap-scala#124]
Now that we've had two PRs updating `uap-core` (#118 and #115) recently, would it be possible to publish a new version of this library?

**Comment by phucnh** [comment]
@thyandrecardoso Sorry for the late response. I've released `v0.12.0` and published it to maven. Please check and let me know if any problem.

**Comment by thyandrecardoso** [comment]
Thank you! 👍
