### ISSUE TITLE
Bump to latest core version + crossBuild to 2.12.11

### ISSUE THREAD

**Issue by nitayk** [ua-parser/uap-scala#137]
@phucnh Continuing where we stopped: https://github.com/ua-parser/uap-scala/issues/123
My PR's got merged to the core module :) 

Wasn't sure about the version numbers & wasn't sure about the addition to _crossScalaVersions_ - LMK if something needs to be changed / added

**Comment by phucnh** [comment]
@nitayk Thank you so much.
I have created `0.13.0 release` and pushed it to maven. 
Please check and let me know if any problem.

**Comment by nitayk** [comment]
@phucnh Thanks, working great :)
