### ISSUE TITLE
Use same version of uap-core for Python and Scala versions of UA parser 

### ISSUE THREAD

**Issue by ptkool** [ua-parser/uap-scala#14]
The Python and Scala versions of the parser are using different commits of uap-core. Can we synch them up to reference the same commit? @mattrobenolt

**Comment by mattrobenolt** [comment]
I periodically keep uap-python up to date. I don't keep them religiously in sync though. Not sure what you're asking me here. :)

**Comment by ptkool** [comment]
We are currently using both uap-python and uap-scala and require that they both reference the same uap-core SHA.

uap-python
https://github.com/ua-parser/uap-core/tree/4215e8899c511dc656cff09bd5b16041c76d2542

uap-scala (earlier version of uap-core)
https://github.com/ua-parser/uap-core/tree/49b141ffe86d5138c332f733d6b2007675bbeb43 

Would it be possible to update uap-scala?

**Comment by humanzz** [comment]
I've updated to the latest uap-core in this [commit](https://github.com/ua-parser/uap-scala/commit/b0ab839607113d4e28bc17c53c512c417f7885ef).

**Comment by ptkool** [comment]
@humanzz Can you up update `uap-core` for `uap-python` to the same commit?

**Comment by humanzz** [comment]
I'm afraid I only have permissions to uap-scala and not uap-python. One of its maintainers have to do that.

**Comment by mattrobenolt** [comment]
I'm not gonna lie, assuming that all libraries always use the same sha of uap-core is not really going to be feasible. 

Fortunately though, there's nothing requiring this to happen in at least uap-python. You can supply your own list. Just set the `UA_PARSER_YAML` environment variable: https://github.com/ua-parser/uap-python/blob/master/ua_parser/user_agent_parser.py#L450 and you're free to maintain your own explicit sha of uap-core independent of releases.
