### ISSUE TITLE
Scala 3 support

### ISSUE THREAD

**Issue by kyri-petrou** [ua-parser/uap-scala#175]
Hi there 👋 

Do you have any plans to release a Scala 3 version for this library? 

I had a quick look through the library, and it should be relatively straightforward and happy to submit a PR for it. The one thing I'm not sure of is whether I would be able to get the scoverage plugin to work for Scala 2.10 and 2.11 if Scala 3 is to be included

**Comment by phucnh** [comment]
Hi @kyri-petrou 
Currently, I'm not using Scala 3, so I don't have too much knowledge. But I think it's great if this library has a Scala 3 version.
So, PR welcome :D

**Comment by kyri-petrou** [comment]
Done https://github.com/ua-parser/uap-scala/pull/176 🎉

**Comment by kyri-petrou** [comment]
Is there still any interest in this PR by any chance?

**Comment by phucnh** [comment]
I released uap-scala 0.14.0 with scala 3 support. Thanks for your participation
