### ISSUE TITLE
Publish new version to maven repo

### ISSUE THREAD

**Issue by jleider** [ua-parser/uap-scala#19]
Now that uap-core has been recently updated, it would be great to see a new version of uap-scala published to maven. :)

**Comment by travisbrown** [comment]
Hi @jleider! @humanzz published an 0.1.0 release for 2.12 a few days ago, and I'm planning to publish an 0.2.0 release this weekend so that we'll have a cross-built version where all of the artifacts have the same dependencies and same uap-core.

**Comment by travisbrown** [comment]
It's out! https://github.com/ua-parser/uap-scala/releases/tag/v0.2.0
