### ISSUE TITLE
Find new uap-scala maintainers

### ISSUE THREAD

**Issue by travisbrown** [ua-parser/uap-scala#34]
I've been reviewing PRs, managing updates, and publishing uap-scala releases for the last year and a half, but I'm no longer using the library (only because I've left Stripe), and would like to hand off some of these responsibilities to new maintainers.

I'd estimate that I've spent less than an hour per month on uap-scala maintenance this year. I don't have details about how widely adopted the library is, but the Maven Central usage stats have more than doubled in 2018 so far, up to 12,176 downloads from 7,052 unique IPs in September.

If you're using the library and would be interested in talking about taking on maintenance responsibilities, please either reply here or DM me on Twitter at [@travisbrown](https://twitter.com/travisbrown).

/cc @humanzz

**Comment by BenFradet** [comment]
We might be interested as we're using uap-java for now but would like to transition

**Comment by phucnh** [comment]
We are using uap-scala. Would like to maintain this repository.
