### ISSUE TITLE
Not working. Tests are failing

### ISSUE THREAD

**Issue by dkovalenko** [ua-parser/uap-scala#6]
$ sbt
[info] Loading global plugins from /Users/work/.sbt/0.13/plugins
[info] Set current project to uap-scala (in build file:/Users/work/projects/scala/uap-scala/)
> test
[info] Compiling 1 Scala source to /Users/work/projects/scala/uap-scala/target/scala-2.11/classes...
[info] CachingParserSpec
[info] 
[info] Parser should
[info] + parse basic ua
[info] + properly quote replacements
[info] ! properly parse user agents
[error]    YAMLException: : java.io.IOException: Stream closed  (StreamReader.java:198)
[error] org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:198)
[error] org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:62)
[error] org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
[error] ua.parser.ParserSpecBase$$anonfun$1.ua$parser$ParserSpecBase$class$$anonfun$$readCasesConfig$1(ParserSpecBase.scala:77)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$14.apply(ParserSpecBase.scala:55)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$14.apply(ParserSpecBase.scala:54)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(ParserSpecBase.scala:54)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(ParserSpecBase.scala:58)
[error] org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:88)
[error] org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:118)
[error] org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:182)
[error] org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:62)
[error] org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
[error] ua.parser.ParserSpecBase$$anonfun$1.ua$parser$ParserSpecBase$class$$anonfun$$readCasesConfig$1(ParserSpecBase.scala:77)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$14.apply(ParserSpecBase.scala:55)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$14.apply(ParserSpecBase.scala:54)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(ParserSpecBase.scala:54)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(ParserSpecBase.scala:58)
[error] 
[error] Caused by java.io.IOException: Stream closed
[error] org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:88)
[error] org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:118)
[error] org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:182)
[error] org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:62)
[error] org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
[error] ua.parser.ParserSpecBase$$anonfun$1.ua$parser$ParserSpecBase$class$$anonfun$$readCasesConfig$1(ParserSpecBase.scala:77)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$14.apply(ParserSpecBase.scala:55)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$14.apply(ParserSpecBase.scala:54)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(ParserSpecBase.scala:54)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(ParserSpecBase.scala:58)
[info] 
[info] ! properly parse os
[error]    YAMLException: : java.io.IOException: Stream closed  (StreamReader.java:198)
[error] org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:198)
[error] org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:62)
[error] org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
[error] ua.parser.ParserSpecBase$$anonfun$1.ua$parser$ParserSpecBase$class$$anonfun$$readCasesConfig$1(ParserSpecBase.scala:77)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$19.apply(ParserSpecBase.scala:63)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$19.apply(ParserSpecBase.scala:62)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$6.apply(ParserSpecBase.scala:62)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$6.apply(ParserSpecBase.scala:66)
[error] org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:88)
[error] org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:118)
[error] org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:182)
[error] org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:62)
[error] org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
[error] ua.parser.ParserSpecBase$$anonfun$1.ua$parser$ParserSpecBase$class$$anonfun$$readCasesConfig$1(ParserSpecBase.scala:77)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$19.apply(ParserSpecBase.scala:63)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$19.apply(ParserSpecBase.scala:62)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$6.apply(ParserSpecBase.scala:62)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$6.apply(ParserSpecBase.scala:66)
[error] 
[error] Caused by java.io.IOException: Stream closed
[error] org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:88)
[error] org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:118)
[error] org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:182)
[error] org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:62)
[error] org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
[error] ua.parser.ParserSpecBase$$anonfun$1.ua$parser$ParserSpecBase$class$$anonfun$$readCasesConfig$1(ParserSpecBase.scala:77)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$19.apply(ParserSpecBase.scala:63)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$19.apply(ParserSpecBase.scala:62)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$6.apply(ParserSpecBase.scala:62)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$6.apply(ParserSpecBase.scala:66)
[info] 
[info] ! properly parse device
[error]    YAMLException: : java.io.IOException: Stream closed  (StreamReader.java:198)
[error] org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:198)
[error] org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:62)
[error] org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
[error] ua.parser.ParserSpecBase$$anonfun$1.ua$parser$ParserSpecBase$class$$anonfun$$readCasesConfig$1(ParserSpecBase.scala:77)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$8.apply(ParserSpecBase.scala:70)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$8.apply(ParserSpecBase.scala:70)
[error] org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:88)
[error] org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:118)
[error] org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:182)
[error] org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:62)
[error] org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
[error] ua.parser.ParserSpecBase$$anonfun$1.ua$parser$ParserSpecBase$class$$anonfun$$readCasesConfig$1(ParserSpecBase.scala:77)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$8.apply(ParserSpecBase.scala:70)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$8.apply(ParserSpecBase.scala:70)
[error] 
[error] Caused by java.io.IOException: Stream closed
[error] org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:88)
[error] org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:118)
[error] org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:182)
[error] org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:62)
[error] org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
[error] ua.parser.ParserSpecBase$$anonfun$1.ua$parser$ParserSpecBase$class$$anonfun$$readCasesConfig$1(ParserSpecBase.scala:77)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$8.apply(ParserSpecBase.scala:70)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$8.apply(ParserSpecBase.scala:70)
[info] 
[info] 
[info] Total for specification CachingParserSpec
[info] Finished in 160 ms
[info] 5 examples, 7 expectations, 0 failure, 3 errors
[info]  
[info] ParserSpec
[info] 
[info] Parser should
[info] + parse basic ua
[info] + properly quote replacements
[info] ! properly parse user agents
[error]    YAMLException: : java.io.IOException: Stream closed  (StreamReader.java:198)
[error] org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:198)
[error] org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:62)
[error] org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
[error] ua.parser.ParserSpecBase$$anonfun$1.ua$parser$ParserSpecBase$class$$anonfun$$readCasesConfig$1(ParserSpecBase.scala:77)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$14.apply(ParserSpecBase.scala:55)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$14.apply(ParserSpecBase.scala:54)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(ParserSpecBase.scala:54)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(ParserSpecBase.scala:58)
[error] org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:88)
[error] org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:118)
[error] org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:182)
[error] org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:62)
[error] org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
[error] ua.parser.ParserSpecBase$$anonfun$1.ua$parser$ParserSpecBase$class$$anonfun$$readCasesConfig$1(ParserSpecBase.scala:77)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$14.apply(ParserSpecBase.scala:55)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$14.apply(ParserSpecBase.scala:54)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(ParserSpecBase.scala:54)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(ParserSpecBase.scala:58)
[error] 
[error] Caused by java.io.IOException: Stream closed
[error] org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:88)
[error] org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:118)
[error] org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:182)
[error] org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:62)
[error] org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
[error] ua.parser.ParserSpecBase$$anonfun$1.ua$parser$ParserSpecBase$class$$anonfun$$readCasesConfig$1(ParserSpecBase.scala:77)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$14.apply(ParserSpecBase.scala:55)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$14.apply(ParserSpecBase.scala:54)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(ParserSpecBase.scala:54)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(ParserSpecBase.scala:58)
[info] 
[info] ! properly parse os
[error]    YAMLException: : java.io.IOException: Stream closed  (StreamReader.java:198)
[error] org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:198)
[error] org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:62)
[error] org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
[error] ua.parser.ParserSpecBase$$anonfun$1.ua$parser$ParserSpecBase$class$$anonfun$$readCasesConfig$1(ParserSpecBase.scala:77)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$19.apply(ParserSpecBase.scala:63)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$19.apply(ParserSpecBase.scala:62)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$6.apply(ParserSpecBase.scala:62)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$6.apply(ParserSpecBase.scala:66)
[error] org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:88)
[error] org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:118)
[error] org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:182)
[error] org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:62)
[error] org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
[error] ua.parser.ParserSpecBase$$anonfun$1.ua$parser$ParserSpecBase$class$$anonfun$$readCasesConfig$1(ParserSpecBase.scala:77)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$19.apply(ParserSpecBase.scala:63)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$19.apply(ParserSpecBase.scala:62)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$6.apply(ParserSpecBase.scala:62)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$6.apply(ParserSpecBase.scala:66)
[error] 
[error] Caused by java.io.IOException: Stream closed
[error] org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:88)
[error] org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:118)
[error] org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:182)
[error] org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:62)
[error] org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
[error] ua.parser.ParserSpecBase$$anonfun$1.ua$parser$ParserSpecBase$class$$anonfun$$readCasesConfig$1(ParserSpecBase.scala:77)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$19.apply(ParserSpecBase.scala:63)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$19.apply(ParserSpecBase.scala:62)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$6.apply(ParserSpecBase.scala:62)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$6.apply(ParserSpecBase.scala:66)
[info] 
[info] ! properly parse device
[error]    YAMLException: : java.io.IOException: Stream closed  (StreamReader.java:198)
[error] org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:198)
[error] org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:62)
[error] org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
[error] ua.parser.ParserSpecBase$$anonfun$1.ua$parser$ParserSpecBase$class$$anonfun$$readCasesConfig$1(ParserSpecBase.scala:77)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$8.apply(ParserSpecBase.scala:70)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$8.apply(ParserSpecBase.scala:70)
[error] org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:88)
[error] org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:118)
[error] org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:182)
[error] org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:62)
[error] org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
[error] ua.parser.ParserSpecBase$$anonfun$1.ua$parser$ParserSpecBase$class$$anonfun$$readCasesConfig$1(ParserSpecBase.scala:77)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$8.apply(ParserSpecBase.scala:70)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$8.apply(ParserSpecBase.scala:70)
[error] 
[error] Caused by java.io.IOException: Stream closed
[error] org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:88)
[error] org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:118)
[error] org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:182)
[error] org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:62)
[error] org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
[error] ua.parser.ParserSpecBase$$anonfun$1.ua$parser$ParserSpecBase$class$$anonfun$$readCasesConfig$1(ParserSpecBase.scala:77)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$8.apply(ParserSpecBase.scala:70)
[error] ua.parser.ParserSpecBase$$anonfun$1$$anonfun$apply$mcV$sp$8.apply(ParserSpecBase.scala:70)
[info] 
[info] 
[info] Total for specification ParserSpec
[info] Finished in 162 ms
[info] 5 examples, 7 expectations, 0 failure, 3 errors
[info]  
[error] Error: Total 10, Failed 0, Errors 6, Passed 4
[error] Error during tests:
[error] 	ua.parser.CachingParserSpec
[error] 	ua.parser.ParserSpec
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 9 s, completed 24.03.2016 11:10:35

**Comment by dzlab** [comment]
i've a similar problem when running `sbt test`, how I can successfully build with `sbt package`

**Comment by humanzz** [comment]
I've updated the library and did some refactoring.

sbt test and package are working for me. I'll close this issue. Please try the latest version, and if the problem persists feel free to reopen.
