### ISSUE TITLE
Publish uap-scala to maven

### ISSUE THREAD

**Issue by humanzz** [ua-parser/uap-scala#8]
It'd be great if we can get this library published to maven.

I forked the the repo at https://github.com/humanzz/uap-scala and I updated some configs and all tests/builds are passing.

I haven't published stuff to maven before, but I'm willing to help if needed.

**Comment by russellwhitaker** [comment]
I'm thinking the Scala port is long abandoned; it would be very cool if you got committer privileges to bring it up to date. My own frustration with the apparently abandoned Java port a couple years ago drove me to write a Clojure implementation, uap-clj.

**Comment by humanzz** [comment]
It does seem to be long abandoned indeed. I [got in touch with the original committer](https://twitter.com/humanzz/status/748136148866863104), and he directed me to the ua-parser google group so [I posted there](https://groups.google.com/forum/#!topic/ua-parser/wADyjxljJu4) trying to get access.
Let's see how that goes!

I'm trying to revive this because I need it in a Spark application. I don't know much about Clojure so I tried to follow the uap-clj guide for java, but it didn't work for me so I just tried to revive this. It'd be nice to bring it to an easily useable up to date state!

**Comment by russellwhitaker** [comment]
@humanzz I'm guessing you tried the Java API of uap-clj using v1.2.0; it seems I deployed an artifact to Clojars missing the API class files (https://github.com/russellwhitaker/uap-clj/issues/28). I fixed that with v1.2.2, so the README example does now work (https://github.com/russellwhitaker/uap-clj). Try it and let me know.

**Comment by humanzz** [comment]
@russellwhitaker I'll give it a try and let you know.

**Comment by russellwhitaker** [comment]
@humanzz thanks, looking forward to hearing about it.

**Comment by humanzz** [comment]
@russellwhitaker it works. Well, if I managed to make it work earlier, I wouldn't have worked on the scala one I guess... where was this when I needed it?! :)

Anyways, on the scala front, I am now a scala maintainer and I plan to publish the scala version. I started the process at https://issues.sonatype.org/browse/OSSRH-23440

**Comment by russellwhitaker** [comment]
Sorry the earlier Clojure version was distributed without artifacts, but it's good that you're actively resurrecting the Scala version. Looks like the Clojure and Scala versions will be actively maintained, so the absence of a maintained native Java version won't affect anyone (as long as they import either version.)

**Comment by humanzz** [comment]
It's not available in maven. Updated the README with instructions on how to get it.
